---
- name: Create path for Vim-plug
  file:
    path=~/.vim/autoload
    state=directory
    mode=0755

- name: Install Vim-plug
  get_url:
    url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest=~/.vim/autoload/plug.vim

- name: Copy dotfiles
  copy:
    src=~/dotfiles/{{ item }}
    dest=~/.{{ item }}
  with_items:
    - .zshrc
    - .vimrc
    - .gitconfig
    - .gitignore_global
    - .gitk
    - .osx
    - .osx_aliases
    - .shell_aliases
    - .bash_profile

- name: Install/update Vim plugins
  command: vim +PluginInstall +qall
