---
- name: Install homebrew packages
  homebrew:
    name={{ item }}
    state=present
  with_items:
    - colordiff
    - git
    - go
    - nvm
    - python
    - python3
    - vim
    - yarn
    - zplug
    - zsh

- name: Install homebrew cask packages
  homebrew_cask:
    name={{ item }}
    state=present
  with_items:
    - adobe-creative-cloud
    - appcleaner
    - atom
    - docker
    - dropbox
    - gpgtools
    - java
    - jetbrains-toolbox
    - keepingyouawake
    - qbittorrent
    - robo-3t
    - sketchup
    - slack
    - sourcetree
    - spectacle
    - spotify
    - steam
    - vlc
